name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - master  # master 브랜치에 푸시될 때 트리거

jobs:
  build:
    runs-on: ubuntu-latest    ## 실행 환경 (개발서버가 ubuntu 최신 버전이다)

    steps: 
    
    
    # 코드 체크아웃
    - name: Checkout repository  ## 파이프라인시 나타나는 메시지
      uses: actions/checkout@v2  ## git action 에서 사용하는 플러그인 (master 브랜치를 복사해오는 스크립트)


    # JDK 17 설정
    - name: Set up JDK 17
      uses: actions/setup-java@v1  ## 자바 설치하는 git action 플러그인
      with:
        java-version: '17'


    # 빌드하기 (빌드 실행 명령 gradlew 에 실행 권한(+x) 부여한 뒤 빌드)
    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew build


    # 개인키 만들기
    # mkdir
    # echo : 개인키 값이 등록된 환경변수({ secrets.SERVER_SSH_KEY }) 값을 읽어 개인키 파일 id_rsa 만들기
    #    SERVER_SSH_KEY : 이 이름으로 github 에 환경변수를 등록해 둬야 한다. (Settings - Secrets and variables - Actions - New repository secret)
    # chmod : 나만 읽기/쓰기 권한 가진다. 너희는 아무 것도 할 수 없어.
    - name: Set SSH key permissions
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}


    # 접속해야 할 운영서버의 정보를 등록한다. (운영서버IP - 13.124.83.239)
    - name: Add known_hosts
      run: |
        ssh-keyscan -t ed25519 13.124.83.239 >> ~/.ssh/known_hosts

    #- name: 기존프로세스 종료 
    #  run: |
    #    kill -9 $(ps -ef | grep devops | grep -v grep | head -n 1 | awk '{print $2}') || true


    # 운영서버로 jar 복사하기 (운영서버IP - 13.124.83.239)
    - name: Deploy to Server
      run: scp build/libs/*.jar ubuntu@13.124.83.239:~/


    # 운영서버에 접속해서 java -jar 명령 내리기. java -jar 명령 내리기 전에 기존 실행 중인 java 실행 명령 먼저 끄기 (운영서버IP - 13.124.83.239)
    # nohup : 터미널이 꺼져도 java -jar 실행 중인 명령을 끄지 마라.
    # 로그들은 파일로 남겨라. (log.txt)
    # 마지막 & : 백그라운드 실행
    - name: Run SSH commands
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@13.124.83.239 << 'EOF'
          pkill -f 'java -jar' || true
          nohup java -jar ~/devops_step0-0.0.1-SNAPSHOT.jar > log.txt 2>&1 &
        EOF
